version: '3'
 
services:
    api:
        container_name: api
        build: .
        ports:
            - "3000:3000" 
        links:
            - redis
            - mongo
        environment:
            REDIS_HOST: redis://redis:6379
            MONGO_HOST: mongodb://mongo:27017
            MONO_DATABASE_NAME: sms-to-impress
            EXPRESS_HOST: 3000
            EXPRESS_HEADERS_ALLOW: "X-Requested-With, Content-Type, Accept, Authorization"
            EXPRESS_HEADERS_EXPOSE: "Message"
            EXPRESS_HEADERS_ORIGIN: "*"
            EXPRESS_HEADERS_METHODS: "POST, GET, PUT, DELETE, OPTIONS, PATCH"

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017" 
        command: "--smallfiles --logpath=/dev/null --quiet"
        volumes:
            - ./.data/mongo:/data/db

    redis:
        container_name: redis
        image: redis:alpine
        volumes:
            - ./.data/redis:/data