version: '3'

services:
    api:
        container_name: api
        build:
            context: ../
            dockerfile: .build/dev.dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ../:/development
        environment:
            EXPRESS_PORT: 3000