version: '3'

services:
    api:
        container_name: api
        build:
            context: ../
            dockerfile: .build/prod.dockerfile
        ports:
            - "3000:3000"
        environment:
            EXPRESS_PORT: 3000